export const LOAD_DATA_REQUEST 	= 'LOAD_DATA_REQUEST'
export const LOAD_DATA_FAILURE 	= 'LOAD_DATA_FAILURE'
export const LOAD_CUSTOMERS_DATA_SUCCESS 	= 'LOAD_CUSTOMERS_DATA_SUCCESS'
export const LOAD_PRODUCTS_DATA_SUCCESS 	= 'LOAD_PRODUCTS_DATA_SUCCESS'

